### ISSUE TITLE
New product Sage Final Accounts

### ISSUE THREAD

**Issue by joydore** [adamgeorgeson/versionkeeper_old#34]
The online accounts product will be going live next weekend.  Please set this up as a new product on this system

**Comment by joydore** [comment]
Hi Adam,

Yes and no.

We’ve been calling the product Accounts Production Online for almost the full 18 months duration of the project but we’ve gone live with the name Final Accounts Online.  I believe the ‘Online’ part is to be dropped soon.

We should really use the proper name, to avoid confusion.  Is that going to cause you a problem?

Regards,

Joy

Joy Dore

Development Team Leader
Technology Group | Sage UK & Ireland

T. +44 (0)161 868 4763
joy.dore@sage.commailto:joy.dore@sage.com | www.sage.co.ukhttp://www.sage.co.uk/

Exchange Quay, Manchester, M5 3ED
[Sage_Logo green]

**Comment by adamgeorgeson** [comment]
@joydore No problem at all. I'll get it changed later on to 'Final Accounts' to avoid confusion.

**Comment by joydore** [comment]
Thanks ☺

Joy
